### ISSUE TITLE
Maybe add docs and a CLA

### ISSUE THREAD

**Issue by ghost** [SmoreSoftware/SmoreBot#10]
just a suggestion where I can help

**Comment by Chrono-byte** [comment]
You have been posting this to a lot of bots lately?

**Comment by ghost** [comment]
cla? just in dtel I think 🤔

**Comment by ghost** [comment]
and thats something I can contribute to

**Comment by Chrono-byte** [comment]
https://discord.gg/6P6MNAU Join here, mention me in general

**Comment by ghost** [comment]
joined, I listen by the name ThatGreekGuy#7780

**Comment by ghost** [comment]
**when u realise GitHub has wikis** delet that

**Comment by Jdender** [comment]
We will get to docs when we can. I am closing this issue because "mention me on discord" doesn't help the discussion.
