### ISSUE TITLE
Wheres the music look at the repo's desc

### ISSUE THREAD

**Issue by CleverSource** [SmoreSoftware/SmoreBot#3]
???

**Comment by tjreigh** [comment]
I apologize for this. The repo description should be updated. Music is coming soon, I just need to get it to a state without any memory leaks.

**Comment by Asheiou** [comment]
Smore Music should probably exist.

**Comment by Chrono-byte** [comment]
Will start work on today!

**Comment by jdenderplays** [comment]
I would say we don't have the hosting power or the dev power to pull such a thing off. It would be a lot simpler to just update the description.
